---
- name: Add spatial-server system group
  group:
    name: "{{ dirt_system_group }}"
    state: present

- name: Add spatial-server system user
  user:
    name: "{{ dirt_system_user }}"
    shell: /bin/bash
    group: "{{ dirt_system_group }}"
    groups: "{{ dirt_system_groups }}"
    append: yes
    createhome: yes
    home: "{{ dirt_system_user_home }}"


- name: Install Node Version Manager
  include_role:
    name: onaio.nvm
  vars:
    nvm_user: "{{ dirt_system_user }}"
    nvm_group: "{{ dirt_system_group }}"
    nvm_node_version: "{{ dirt_nvm_node_version }}"
    nvm_install_path: "{{ dirt_nvm_install_path }}"
    nvm_node_dir: "{{ dirt_nvm_node_dir }}"
    nvm_npm_path: "{{ dirt_nvm_npm_path }}"
    nvm_version: "{{ dirt_nvm_version }}"

- name: Download Dirt
  become: true
  become_user: "{{ dirt_system_user }}"
  git:
    repo: "{{ dirt_git_url }}"
    dest: "{{ dirt_checkout_path }}"
    version: "{{ dirt_version }}"
    depth: 1

- name: Install Dirt npm packages
  become: true
  become_user: "{{ chubbs_system_user }}"
  npm:
    path: "{{ chubbs_checkout_path }}"
    executable: "{{ chubbs_nvm_npm_path }}"
  environment:
    PATH: "{{ chubbs_nvm_node_dir }}/bin:{{ ansible_env.PATH }}"

- name: Copy dirt server index.js to config directory
  template:
    src: dirt_checkout_path/config/index.js.j2
    dest: "{{ dirt_checkout_path }}/config/index.js"
    mode: 0644

- name: Make the new codebase current
  become: true
  become_user: "{{ dirt_system_user }}"
  file:
    force: yes
    state: link
    dest: "{{ dirt_codebase_path }}"
    src: "{{ dirt_checkout_path }}"

- name: Configure PM2
  include_tasks: pm2.yml
