---
- name: Add spatial-server system group
  group:
    name: "{{ dirt_system_group }}"
    state: present

- name: Add spatial-server system user
  user:
    name: "{{ dirt_system_user }}"
    shell: /bin/bash
    group: "{{ dirt_system_group }}"
    groups: "{{ dirt_system_groups }}"
    append: yes
    createhome: yes
    home: "{{ dirt_system_user_home }}"


- name: Install Node Version Manager
  include_role:
    name: onaio.nvm
  vars:
    nvm_user: "{{ dirt_system_user }}"
    nvm_group: "{{ dirt_system_group }}"
    nvm_node_version: "{{ dirt_nvm_node_version }}"
    nvm_install_path: "{{ dirt_nvm_install_path }}"
    nvm_node_dir: "{{ dirt_nvm_node_dir }}"
    nvm_npm_path: "{{ dirt_nvm_npm_path }}"
    nvm_version: "{{ dirt_nvm_version }}"

- name: Install dependencies
  apt:
    update_cache: yes
    name: "{{ item }}"
  with_items: "{{ dirt_apt_dependencies }}"
  tags:
    - mapnik

# install mapnik
- name: Clone the mapnik repo
  git:
    repo: "{{ dirt_mapnik_git_url }}"
    version: "{{ dirt_mapnik_version }}"
    depth: 10
    dest: "{{ dirt_mapnik_install_dir }}"
  tags:
    - mapnik

- name: Run the bootstrap file # noqa 301 305
  shell: ./bootstrap.sh
  args:
    chdir: "{{ dirt_mapnik_install_dir }}"
  tags:
    - mapnik

- name: Run the configure script # noqa 301 305
  shell: ./configure  CUSTOM_CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" CXX="clang++-3.8" CC="clang-3.8"
  args:
    chdir: "{{ dirt_mapnik_install_dir }}"
  tags:
    - mapnik

- name: Make Install
  make:
    target: install
    chdir: "{{ dirt_mapnik_install_dir }}"
  tags:
    - mapnik

- name: Download PGRestAPI
  become: true
  become_user: "{{ dirt_system_user }}"
  git:
    repo: "{{ dirt_git_url }}"
    dest: "{{ dirt_checkout_path }}"
    version: "{{ dirt_version }}"
    depth: 1

- name: Install node requirements
  include_tasks: "node-dependencies-{{ dirt_node_deps_install_method }}.yml"

- name: Copy dirt server settings.js to settings directory
  template:
    src: dirt_checkout_path/settings/settings.js.j2
    dest: "{{ dirt_checkout_path }}/settings/settings.js"
    mode: 0644

- name: Make the new codebase current
  become: true
  become_user: "{{ dirt_system_user }}"
  file:
    force: yes
    state: link
    dest: "{{ dirt_codebase_path }}"
    src: "{{ dirt_checkout_path }}"

- name: Configure PM2
  include_tasks: pm2.yml
