---
- name: Install Node.js Packages
  become: true
  become_user: "{{ dirt_system_user }}"
  npm:
    global: yes
    name: pm2
    executable: "{{ dirt_nvm_npm_path }}"
    version: "{{ dirt_nvm_pm2_version }}"
  environment:
    PATH: "{{ dirt_nvm_node_dir }}/bin:{{ ansible_env.PATH }}"

- name: delete specific pm2 process
  become: true
  become_user: "{{ dirt_system_user }}"
  shell: "{{ dirt_nvm_pm2_path }} delete {{ dirt_service_name }}"
  # this shell fails if the process has not yet been started
  ignore_errors: True
  environment:
    PATH: "{{ dirt_nvm_node_dir }}/bin:{{ ansible_env.PATH }}"
    HOME: "{{ dirt_system_user_home }}"
  notify:
    - "reload pm2"

- name: start pm2 app
  become: true
  become_user: "{{ dirt_system_user }}"
  shell: "{{ dirt_nvm_pm2_path }} start index.js -i 0 -n {{ dirt_service_name }}"
  args:
    chdir: "{{ dirt_codebase_path }}"
  environment:
    PATH: "{{ dirt_nvm_node_dir }}/bin:{{ ansible_env.PATH }}"
    HOME: "{{ dirt_system_user_home }}"
    POSTGRES_CONNECTION: "{{ dirt_db_url }}"
    TABLE_COLUMN: "{{ dirt_table_column }}"
    TABLE_NAME: "{{ dirt_table_name }}"
    SERVER_PORT: "{{ dirt_port }}"
    SERVER_LOGGER: "{{ dirt_server_logging }}"
    FORMS_ENDPOINT: "{{ dirt_onadata_forms_endpoint }}"
    CORS_ORIGINS: "{{ dirt_cors_whitelist }}"
  notify:
    - "reload pm2"

- name: save the current PM2 running list
  become: true
  become_user: "{{ dirt_system_user }}"
  shell: "{{ dirt_nvm_pm2_path }} save"
  environment:
    PATH: "{{ dirt_nvm_node_dir }}/bin:{{ ansible_env.PATH }}"
    HOME: "{{ dirt_system_user_home }}"
  notify:
    - "reload pm2"

- name: delete the old startup file
  become: true
  become_user: "root"
  shell: "{{ dirt_nvm_pm2_path }} unstartup {{ dirt_init_system }} -u {{ dirt_system_user }}"
  environment:
    PATH: "{{ dirt_nvm_node_dir }}/bin:{{ ansible_env.PATH }}"
  ignore_errors: True
  notify:
    - "reload pm2"

- name: Cleanup pm2 processes
  become: true
  become_user: "root"
  shell: "killall -u {{ dirt_system_user }}"
  # for local testing you might need the following
  # shell: "pkill -u {{ dirt_system_user }}"

- name: generate an PM2 init service file
  become: true
  become_user: "root"
  command: "{{ dirt_nvm_pm2_path }} startup {{ dirt_init_system }} -u {{ dirt_system_user }} --hp {{ dirt_system_user_home }}"
  environment:
    PATH: "{{ dirt_nvm_node_dir }}/bin:{{ ansible_env.PATH }}"
  notify:
    - "reload pm2"

- name: Enable the PM2 service
  service:
    name: "pm2-{{ dirt_service_name }}"
    enabled: yes
