---
dependency:
  name: galaxy
driver:
  name: docker
# lint: yamllint
platforms:
  # add ubuntu 20 and 22 platforms
  - name: dirt-ubuntu
    image: solita/ubuntu-systemd:18.04
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
  # lint:
  #   name: ansible-lint
  #   enabled: true
scenario:
  name: default
  test_sequence:
    - lint
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: ansible
