---
- name: Verify
  hosts: zebra-ubuntu
  become: true
  tasks:
    - include_vars:
        dir: ../../defaults
        ignore_unknown_extensions: True
        extensions:
          - ""
          - "yaml"
          - "yml"
          - "json"
